server:
  port: 9246
spring:
  application:
    name: rainy-cloud-nacos-payment8001
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #加上allowPublicKeyRetrieval=true 访问Druid的时候不会出错
    url: jdbc:mysql://localhost:3306/RainySpring?useSSL=false&characterEncoding=utf-8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: Neeko142