server:
  port: 9245



spring:
  application:
    name: rainy-cloud-hystrix-payment
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    #加上allowPublicKeyRetrieval=true 访问Druid的时候不会出错
    url: jdbc:mysql://localhost:3306/RainySpring?useSSL=false&characterEncoding=utf-8&useUnicode=true&allowPublicKeyRetrieval=true
    username: root
    password: Neeko142

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
