server:
  port: 8412

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
      #集群版 加入到eureka集群之中

spring:
  application:
    name: rainy-cloud-nacos-comsumer8412